In [1]:
import requests as req
from bs4 import BeautifulSoup as bs
import pandas as pd

In [2]:
# 네이버 증권 > 시장지표 > 환율 리스트 크롤링 (통화명, 매매기준율)
U_A = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"}
res = req.get("https://finance.naver.com/marketindex/exchangeList.naver", headers = U_A)
html = bs(res.text, "lxml")
curr = html.select("td.tit > a")
sale = html.select("td.sale")
len(curr) # 58
len(sale) # 58

curr_lst = []
sale_lst = []
for i in range(len(curr)) :
    curr_lst.append(curr[i].text.strip())
    sale_lst.append(sale[i].text.strip() + " 원")

result = {"통화명" : curr_lst, "매매기준율" : sale_lst}

df = pd.DataFrame(result, index = range(1, len(curr)+1))
df

              통화명       매매기준율
1          미국 USD  1,360.00 원
2        유럽연합 EUR  1,478.80 원
3   일본 JPY (100엔)    866.99 원
4          중국 CNY    187.24 원
5          홍콩 HKD    174.11 원
6          대만 TWD     42.25 원
7          영국 GBP  1,737.67 원
8          오만 OMR  3,532.65 원
9         캐나다 CAD    997.03 원
10        스위스 CHF  1,493.52 원
11        스웨덴 SEK    128.92 원
12         호주 AUD    905.62 원
13       뉴질랜드 NZD    836.60 원
14         체코 CZK     59.91 원
15         칠레 CLP      1.52 원
16       튀르키예 TRY     42.24 원
17         몽골 MNT      0.40 원
18       이스라엘 ILS    369.57 원
19        덴마크 DKK    198.19 원
20       노르웨이 NOK    129.62 원
21    사우디아라비아 SAR    362.62 원
22       쿠웨이트 KWD  4,434.59 원
23        바레인 BHD  3,607.43 원
24     아랍에미리트 AED    370.26 원
25        요르단 JOD  1,918.19 원
26        이집트 EGP     28.57 원
27         태국 THB     37.19 원
28       싱가포르 SGD  1,008.94 원
29      말레이시아 MYR    289.75 원
30  인도네시아 IDR 100      8.47 원
31        카타르 QAR    373.10 원
32      카자흐스탄 KZT      3.07 원
33       브루나이 BND  1,008.94 원
34         인도 INR     16.35 원
35       파키스탄 PKR      4.89 원
36      방글라데시 BDT     11.59 원
37        필리핀 PHP     23.46 원
38        멕시코 MXN     81.31 원
39        브라질 BRL    263.58 원
40    베트남 VND 100      5.34 원
41  남아프리카 공화국 ZAR     74.32 원
42        러시아 RUB     15.37 원
43        헝가리 HUF      3.85 원
44        폴란드 PLN    347.56 원
45       스리랑카 LKR      4.50 원
46        알제리 DZD     10.10 원
47         케냐 KES     10.26 원
48       콜롬비아 COP      0.35 원
49       탄자니아 TZS      0.52 원
50         네팔 NPR     10.22 원
51       루마니아 RON    297.24 원
52        리비아 LYD    281.16 원
53        마카오 MOP    168.97 원
54        미얀마 MMK      0.65 원
55      에티오피아 ETB     23.67 원
56     우즈베키스탄 UZS      0.11 원
57       캄보디아 KHR      0.33 원
58         피지 FJD    610.37 원