#### Pandas DataFrame - OPEN API 데이터 필터링

In [1]:
import pandas as pd
import requests as req
import json

In [2]:
# API KEY
with open("../data/API_KEYS.json") as f :
    api_keys = json.loads(f.read())

# 공공데이터
# 오픈 API key
serviceKey = api_keys["GO_DATA_KEY"]

# Request Parameter
# base url
url = "http://apis.data.go.kr/B552584/ArpltnInforInqireSvc"
# end point
endpoint = "/getCtprvnRltmMesureDnsty"

req_url = url + endpoint

sidoName = "서울"

# 응답 데이터 관련 요청 변수
pageNo = 1
numOfRows = 100
params = {
    "serviceKey": serviceKey,
    "returnType": "json",
    "numOfRows": numOfRows,
    "pageNo": pageNo,
    "sidoName": sidoName,
    "ver": "1.0",
}

res = req.get(req_url, params=params)
res_data = res.json()
item = res_data["response"]["body"]["items"]

# Open API 데이터의 정보 3개를 확인하는 코드를 작성
result = []
for i in item:
    result.append(
        {
            "dataTime": i["dataTime"],
            "sidoName": i["sidoName"],
            "stationName": i["stationName"],
            "pm10Value": i["pm10Value"],
            "pm25Value": i["pm25Value"],
        }
    )

df = pd.DataFrame(result)
df

            dataTime sidoName stationName pm10Value pm25Value
0   2024-12-20 08:00       서울          중구        49        40
1   2024-12-20 08:00       서울        한강대로        56        36
2   2024-12-20 08:00       서울         종로구        55        38
3   2024-12-20 08:00       서울        청계천로        59        36
4   2024-12-20 08:00       서울          종로        47        26
5   2024-12-20 08:00       서울         용산구        52        34
6   2024-12-20 08:00       서울         광진구        47        31
7   2024-12-20 08:00       서울         성동구        53        31
8   2024-12-20 08:00       서울        강변북로        65        38
9   2024-12-20 08:00       서울         중랑구        52        34
10  2024-12-20 08:00       서울        동대문구        54        30
11  2024-12-20 08:00       서울         홍릉로        50        27
12  2024-12-20 08:00       서울         성북구        47        28
13  2024-12-20 08:00       서울         정릉로        51        32
14  2024-12-20 08:00       서울         도봉구        47        29
15  2024-12-20 08:00       서울         은평구        54        32
16  2024-12-20 08:00       서울        서대문구        52        36
17  2024-12-20 08:00       서울         마포구        49        37
18  2024-12-20 08:00       서울         신촌로        54        37
19  2024-12-20 08:00       서울         강서구        60        39
20  2024-12-20 08:00       서울        공항대로        51        28
21  2024-12-20 08:00       서울         구로구        62        30
22  2024-12-20 08:00       서울        영등포구        52        34
23  2024-12-20 08:00       서울        영등포로        53        34
24  2024-12-20 08:00       서울         동작구        59        39
25  2024-12-20 08:00       서울   동작대로 중앙차로        67        37
26  2024-12-20 08:00       서울         관악구        48        36
27  2024-12-20 08:00       서울         강남구        49        32
28  2024-12-20 08:00       서울         서초구        65        33
29  2024-12-20 08:00       서울        도산대로        66        38
30  2024-12-20 08:00       서울        강남대로        73        41
31  2024-12-20 08:00       서울         송파구        50        30
32  2024-12-20 08:00       서울         강동구        47        32
33  2024-12-20 08:00       서울        천호대로        53        33
34  2024-12-20 08:00       서울         금천구        59        42
35  2024-12-20 08:00       서울        시흥대로        65        29
36  2024-12-20 08:00       서울         강북구        50        33
37  2024-12-20 08:00       서울         양천구        60        40
38  2024-12-20 08:00       서울         노원구        55        37
39  2024-12-20 08:00       서울         화랑로        54        31

In [3]:
# 1. 열 stationName 만 선택하여 출력
df[["stationName"]]

   stationName
0           중구
1         한강대로
2          종로구
3         청계천로
4           종로
5          용산구
6          광진구
7          성동구
8         강변북로
9          중랑구
10        동대문구
11         홍릉로
12         성북구
13         정릉로
14         도봉구
15         은평구
16        서대문구
17         마포구
18         신촌로
19         강서구
20        공항대로
21         구로구
22        영등포구
23        영등포로
24         동작구
25   동작대로 중앙차로
26         관악구
27         강남구
28         서초구
29        도산대로
30        강남대로
31         송파구
32         강동구
33        천호대로
34         금천구
35        시흥대로
36         강북구
37         양천구
38         노원구
39         화랑로

In [4]:
# 2. 열 pm10Value stationName 을 선택하여 모든 행을 출력
df[["stationName", "pm10Value"]]

   stationName pm10Value
0           중구        49
1         한강대로        56
2          종로구        55
3         청계천로        59
4           종로        47
5          용산구        52
6          광진구        47
7          성동구        53
8         강변북로        65
9          중랑구        52
10        동대문구        54
11         홍릉로        50
12         성북구        47
13         정릉로        51
14         도봉구        47
15         은평구        54
16        서대문구        52
17         마포구        49
18         신촌로        54
19         강서구        60
20        공항대로        51
21         구로구        62
22        영등포구        52
23        영등포로        53
24         동작구        59
25   동작대로 중앙차로        67
26         관악구        48
27         강남구        49
28         서초구        65
29        도산대로        66
30        강남대로        73
31         송파구        50
32         강동구        47
33        천호대로        53
34         금천구        59
35        시흥대로        65
36         강북구        50
37         양천구        60
38         노원구        55
39         화랑로        54

In [5]:
# 3. 열 pm10Value 가 50 이상인 행만 출력
type(df["pm10Value"])
df = df.replace({"pm10Value": "-"}, 0)
df[(df["pm10Value"]).astype(int) >= 50]

            dataTime sidoName stationName pm10Value pm25Value
1   2024-12-20 08:00       서울        한강대로        56        36
2   2024-12-20 08:00       서울         종로구        55        38
3   2024-12-20 08:00       서울        청계천로        59        36
5   2024-12-20 08:00       서울         용산구        52        34
7   2024-12-20 08:00       서울         성동구        53        31
8   2024-12-20 08:00       서울        강변북로        65        38
9   2024-12-20 08:00       서울         중랑구        52        34
10  2024-12-20 08:00       서울        동대문구        54        30
11  2024-12-20 08:00       서울         홍릉로        50        27
13  2024-12-20 08:00       서울         정릉로        51        32
15  2024-12-20 08:00       서울         은평구        54        32
16  2024-12-20 08:00       서울        서대문구        52        36
18  2024-12-20 08:00       서울         신촌로        54        37
19  2024-12-20 08:00       서울         강서구        60        39
20  2024-12-20 08:00       서울        공항대로        51        28
21  2024-12-20 08:00       서울         구로구        62        30
22  2024-12-20 08:00       서울        영등포구        52        34
23  2024-12-20 08:00       서울        영등포로        53        34
24  2024-12-20 08:00       서울         동작구        59        39
25  2024-12-20 08:00       서울   동작대로 중앙차로        67        37
28  2024-12-20 08:00       서울         서초구        65        33
29  2024-12-20 08:00       서울        도산대로        66        38
30  2024-12-20 08:00       서울        강남대로        73        41
31  2024-12-20 08:00       서울         송파구        50        30
33  2024-12-20 08:00       서울        천호대로        53        33
34  2024-12-20 08:00       서울         금천구        59        42
35  2024-12-20 08:00       서울        시흥대로        65        29
36  2024-12-20 08:00       서울         강북구        50        33
37  2024-12-20 08:00       서울         양천구        60        40
38  2024-12-20 08:00       서울         노원구        55        37
39  2024-12-20 08:00       서울         화랑로        54        31

In [6]:
# 4. 열 pm10Value 가 50 이상이고, pm25Value가 40 이상인 모든 행 출력
df = df.replace({"pm25Value": "-"}, 0)
df[(df["pm10Value"].astype(int) >= 50) & (df["pm25Value"].astype(int) >= 40)]

            dataTime sidoName stationName pm10Value pm25Value
30  2024-12-20 08:00       서울        강남대로        73        41
34  2024-12-20 08:00       서울         금천구        59        42
37  2024-12-20 08:00       서울         양천구        60        40